### ISSUE TITLE
Please release the Android and Windows versions, thank you.

### ISSUE THREAD

**Issue by e20999** [keijiro/Nsm#31]
Could the author please compile the source code into an Android or Windows version and release it? Thank you. Most of us do not have a compilation environment and do not understand compilation. Thank you very much! Looking forward to good news!

**Comment by keijiro** [comment]
There are no plans to release a Windows version because the official NDI Studio Monitor app is already available. It’s a free and excellent tool for receiving NDI video streams, so there’s no advantage to using Nsm—unless you have a specific reason?

As for Android, [the new requirements](https://support.google.com/googleplay/android-developer/answer/14151465?hl=en) make it difficult to publish freely on the store. Meeting these requirements would involve hiring testers, which isn’t a viable option for me.

**Comment by e20999** [comment]
> There are no plans to release a Windows version because the official NDI Studio Monitor app is already available. It’s a free and excellent tool for receiving NDI video streams, so there’s no advantage to using Nsm—unless you have a specific reason?没有发布 Windows 版本的计划，因为官方的 NDI Studio Monitor 应用程序已经可用。它是一个免费且出色的工具，用于接收 NDI 视频流，因此使用 Nsm 没有任何优势——除非你有特定原因？
> 
> As for Android, [the new requirements](https://support.google.com/googleplay/android-developer/answer/14151465?hl=en) make it difficult to publish freely on the store. Meeting these requirements would involve hiring testers, which isn’t a viable option for me.至于 Android，[新的要求](https://support.google.com/googleplay/android-developer/answer/14151465?hl=en)使得在商店中自由发布变得困难。满足这些要求需要雇用测试人员，这对我来说不是一个可行的选择。

thank you very much.
